### ISSUE TITLE
Improvements for quality or open sourcing of a jasnah-cli project (tracking)

### ISSUE THREAD

**Issue by arktoswb** [nearai/nearai#49]
Release planning: https://www.notion.so/jasnahcom/Releases-b1934410118446afaebfda7c7851c568

- [x] Rename jasnah-cli to `nearai`. Repo name is `nearai` (@arktoswb )

# Security & Auth
- [x] Move database access behind web server (Hub)
- [x] Login and permission writes via NEAR accounts

# Functionality
- [x] ~~Determine what needs to be done to integrate Kubernetes (@mfornet and @cmrfrd )~~
- [x] We can switch to use decentralized storage - OnMachina is up and running and has lower cost per GB for storage than S3. They are ready to help us onboard (they expect TBs of data storage as they need to prove their business model). Their docs: https://docs.onmachina.io/ . They don't currently support s3 clients. There are python bindings for this API: https://opendev.org/openstack/python-swiftclient

# Code Quality  
- [x] Add Lint https://github.com/nearai/jasnah-cli/issues/62 (@cmrfrd )
- [x] Add spelling (@arktoswb)
- [x] Type checking - mypy (@cmrfrd )
- [x] Ci tests - do not merge until you fix (@cmrfrd )

# Release criteria
Can, just by following the README:
- [ ] Download a small LLaMa
- [x] Download a small dataset
- [x] Download an agent
- [ ] Finetune
- [ ] Run benchmarks
- [ ] ... including a benchmark that uses the agent
- [ ] Upload the LoRA
Without having AWS or database credentials locally.

# API
- [ ] Rate limiting for inference
- [ ] Rate limiting for agent calls
- [ ] Rate limiting for benchingmarking & fine-tuning?

**Comment by arktoswb** [comment]
Done or Obsolete
