### ISSUE TITLE
Capabilities Benchmarks (tracking)

### ISSUE THREAD

**Issue by arktoswb** [nearai/nearai#57]
Benchmarks: https://www.notion.so/jasnahcom/Benchmarks-96b7b1497a55460a82e1674e72ae06b6#74fe0990deb94f5583510528c2ab54b4

## General intelligence
- [ ] hellaswag (@cmrfrd)
- [x] MMLU (@cmrfrd)
- [ ] math problems
- [x] livebench https://github.com/livebench/livebench (@arktoswb)

## Coding & Software
- [x] mbpp
- [ ] codeforces (@mfornet)
- [ ] https://paperswithcode.com/dataset/mmlu
- [ ] https://www.swebench.com/ 
- [ ] https://webarena.dev/
- [ ] https://miniwob.farama.org/index.html
- [ ] UI dev
  - there is an approach someone is using for React generation - https://e2b.dev/blog/reacteval-building-llm-benchmark-for-frontend
- [ ] MLE-bench https://x.com/openai/status/1844429536353714427?s=46&t=sWQUZZQb2Gs3QchDRA6vtg
- [ ] Shell commands in-house Near.AI benchmark (@arktoswb)

## DeFi & Finance

- [ ] Back-testing framework
- [ ] Simulated data

## Tooling
- [ ] previous agent task runs (@arktoswb)
- [ ] baekjoon (@mfornet)
- [x] show benchmark evaluation results in the registry https://github.com/nearai/jasnah-cli/issues/77 (@arktoswb)
- [ ] record model effort in evaluation results https://github.com/nearai/jasnah-cli/issues/74 (@arktoswb)
- [x] evaluation table

---------

- [ ] https://x.com/askvenice/status/1825960163112861747 . Would be nice as an example to have this table coming from our benchmarking as an example
- [ ] https://www.notion.so/jasnahcom/Sync-Notes-07e960c7c6154f2f92fe7aec0eb50bbf?pvs=4#68e2142ffe144c2192ee0c7478eac838 Practical example of a CLI program I want that Claude was ok at building from the first try. Can be a good “vibe check” for us
